/* ================= i18n: UI strings [mn, en] ================= */
const I = {
  brand: ['Улаанбаатар', 'Ulaanbaatar'],
  slogan: ['Бизнес эрхлэгчдийг дэмжих жил', 'Year of Supporting Entrepreneurs'],
  homeAria: ['ulaanbaatar.mn нүүр хуудас', 'ulaanbaatar.mn home'],
  home: ['Нүүр хуудас', 'Home'],
  search: ['Хайх', 'Search'],
  searchPh: ['Үйлчилгээ, мэдээ, төсөл хайх', 'Search services, news, projects'],
  login: ['ДАН-аар нэвтрэх', 'Sign in with DAN'],
  loginShort: ['Нэвтрэх', 'Sign in'],
  menu: ['Цэс', 'Menu'],
  themeLight: ['Гэрэлтэй горим', 'Light mode'],
  themeDark: ['Харанхуй горим', 'Dark mode'],
  a11yMode: ['Харааны бэрхшээлтэй хувилбар', 'Low-vision mode'],
  a11yOn: ['Том үсэг, өндөр тодролтой горим асаалаа', 'Large text, high-contrast mode on'],
  a11yOff: ['Энгийн харагдац руу буцлаа', 'Back to the standard view'],
  hotlineShort: ['Лавлах утас', 'Hotline'],
  close: ['Хаах', 'Close'],
  weather: ['Цаг агаар', 'Weather'],
  cloudy: ['Үүлэрхэг', 'Cloudy'],
  aqi: ['Агаарын чанар', 'Air quality'],
  traffic: ['Түгжрэл', 'Traffic'],
  busy: ['Ачаалалтай', 'Busy'],
  more: ['Дэлгэрэнгүй', 'Details'],
  todayRange: ['Өнөөдөр', 'Today'],
  nav_services: ['Үйлчилгээ', 'Services'],
  nav_news: ['Мэдээ', 'News'],
  nav_build: ['Бүтээн байгуулалт', 'Development'],
  nav_data: ['Хотын өгөгдөл', 'City data'],
  nav_open: ['Ил тод байдал', 'Transparency'],
  nav_about: ['Хотын тухай', 'About the city'],
  cta_report: ['Эрсдэл мэдээлэх', 'Report a hazard'],
  cta_vote: ['Санал өгөх', 'Have your say'],
  urgent: ['Яаралтай', 'Urgent'],
  dismiss: ['Анхааруулгыг хаах', 'Dismiss alerts'],
  notify: ['Мэдэгдэл авах', 'Get notified'],
  notifyOn: ['Энэ анхааруулгын шинэчлэлийг мэдэгдэнэ', "We'll notify you about updates"],
  affected: ['Хамрах хүрээ', 'Affected area'],
  period: ['Хугацаа', 'When'],
  advice: ['Зөвлөмж', 'What to do'],

  breaking: ['Шуурхай мэдээ', 'Latest'],
  liveUpd: ['Шууд шинэчлэгдэж байна', 'Updating live'],
  isNew: ['Шинэ', 'New'],
  allNews: ['Бүх мэдээ', 'All news'],
  read: ['Унших', 'Read'],
  minRead: ['{n} мин унших', '{n} min read'],
  views: ['үзэлт', 'views'],
  govNews: ['Засаг даргын мэдээ', "Governor's news"],
  govRole: ['Нийслэлийн Засаг дарга, Улаанбаатар хотын Захирагч Б.Пүрэвдагва', 'Governor of the Capital City and Mayor of Ulaanbaatar, B. Purevdagva'],
  govLetter: ['Засаг даргад захидал бичих', 'Write to the Governor'],
  govSec: ['Нийслэлийн Засаг дарга', 'The Governor'], govSchedT: ['Засаг даргын ажлын хуваарь', "The Governor's schedule"],
  govSchedD: ['Засаг даргын уулзалт, хуралдаан, ажлын айлчлал: хэзээ, хаана, юу болох вэ.', "The Governor's meetings, sessions and site visits: when, where and what."],
  govName: ['Б.Пүрэвдагва', 'B. Purevdagva'], govTitle: ['Нийслэлийн Засаг дарга, Улаанбаатар хотын Захирагч', 'Governor of the Capital City and Mayor of Ulaanbaatar'],
  govReception: ['Иргэдийн хүлээн авалт: Мягмар гараг бүр 14:00–16:00, Иргэний танхим', 'Citizen reception: every Tuesday 14:00–16:00, Civic Hall'],
  govBook: ['Хүлээн авалтад бүртгүүлэх', 'Book a reception slot'],
  reportDesc: ['Замын нүх, гэмтсэн гэрэлтүүлэг, аюултай барилга', 'Potholes, broken lights, unsafe structures'],
  voteDesc: ['Санал асуулга, санал хүсэлт', 'Polls and suggestions'],

  hubTitle: ['Өнөөдөр хотод', 'Today in the city'],
  hubDesc: ['Хотын сүүлийн мэдээ, хамгийн их хэрэглэгддэг үйлчилгээ, ойрын арга хэмжээ нэг дор.', 'Latest city news, the most used services and upcoming events in one place.'],
  tab_news: ['Мэдээ', 'News'],
  tab_services: ['Үйлчилгээ', 'Services'],
  tab_events: ['Арга хэмжээ', 'Events'],
  f_all: ['Бүгд', 'All'],
  svcSearch: ['Үйлчилгээ хайх', 'Find a service'],
  online: ['Онлайн', 'Online'],
  inperson: ['Биеэр', 'In person'],
  system: ['Цахим систем', 'E-system'],
  noResults: ['Илэрц олдсонгүй. Өөр үгээр хайж үзнэ үү.', 'No matches. Try another word.'],
  allEvents: ['Бүх арга хэмжээ', 'All events'],
  popularSvc: ['Түгээмэл үйлчилгээ', 'Popular services'],
  allServices: ['Бүх үйлчилгээ', 'All services'],
  sitPromoT: ['Хүүхэд төрсөн үү, бизнес эхлүүлэх үү?', 'New baby? Starting a business?'],
  sitPromoD: ['Нэг үйл явдалд хэрэгтэй бүх үйлчилгээг дарааллаар нь харуулна.', 'See every service a life event needs, in order.'],
  sitPromoB: ['Алхмуудыг харах', 'See the steps'],

  sitTitle: ['Амьдралын нөхцөл байдал', 'Life events'],
  sitDesc: ['Нэг үйл явдалд хэрэгтэй бүх үйлчилгээг дарааллаар нь. Алхам бүрийг дуусгах тусам явц тань хадгалагдана.', 'Every service a life event needs, in order. Your progress is saved as you go.'],
  stepsN: ['{n} алхам', '{n} steps'],
  stepsOnline: ['{n} алхам, {o} нь онлайн', '{n} steps, {o} online'],
  progress: ['Явц', 'Progress'],
  doneOf: ['{d}/{n} алхам дууссан', '{d} of {n} steps done'],
  markDone: ['Дууссан гэж тэмдэглэх', 'Mark as done'],
  undo: ['Буцаах', 'Undo'],
  applyOnline: ['Онлайнаар хүсэх', 'Apply online'],
  book: ['Цаг захиалах', 'Book a visit'],
  nextStep: ['Дараагийн алхам', 'Next step'],
  doneLbl: ['Дууссан', 'Done'],
  restart: ['Дахин эхлэх', 'Start over'],
  allDone: ['Бүх алхам дууслаа. Баяр хүргэе!', 'All steps complete. Congratulations!'],
  allDoneD: ['Шийдвэрлэсэн үйлчилгээнүүдийн баримт Миний булан хэсэгт хадгалагдсан.', 'Records of each service are kept in My page.'],
  stepSent: ['Хүсэлт илгээгдлээ', 'Request sent'],
  pickSlot: ['Тохирох цагаа сонгоно уу', 'Pick a time'],
  confirmBook: ['Цаг баталгаажуулах', 'Confirm visit'],
  booked: ['Цаг захиалагдлаа', 'Visit booked'],
  where: ['Хаана', 'Where'],

  mediaTitle: ['Медиа', 'Media'],
  mediaDesc: ['Хотын видео, шууд дамжуулалт, фото сурвалжилга, подкаст', 'City video, live streams, photo stories and podcasts'],
  m_video: ['Видео', 'Video'], m_live: ['Шууд', 'Live'], m_photo: ['Фото', 'Photos'], m_podcast: ['Подкаст', 'Podcast'],
  watching: ['{n} үзэж байна', '{n} watching'],
  photosN: ['{n} фото', '{n} photos'],
  prev: ['Өмнөх', 'Previous'], next: ['Дараах', 'Next'],
  play: ['Тоглуулах', 'Play'], pause: ['Зогсоох', 'Pause'],
  liveFor: ['Дамжуулалт эхэлснээс', 'Live for'],
  photoCredit: ['Фото: Нийслэлийн хэвлэлийн алба', 'Photo: City press office'],

  projTitle: ['Бүтээн байгуулалт', 'Development'],
  projDesc: ['Нийслэлийн 24 мега төслийн явцыг газрын зураг дээрээс хянаарай. Тойрог дээр дарж томруулна.', 'Follow the 24 flagship projects on the map. Tap a cluster to zoom in.'],
  st_progress: ['Явцад', 'In progress'], st_done: ['Дууссан', 'Completed'], st_planned: ['Эхлэх шатанд', 'Early stage'],
  avgProgress: ['Дундаж гүйцэтгэл', 'Average progress'],
  projectsN: ['{n} төсөл', '{n} projects'],
  completedN: ['{n} дууссан', '{n} completed'],
  budget: ['Төсөв', 'Budget'],
  dueYear: ['Дуусах он', 'Completion'],
  zoomHint: ['Томруулахын тулд Ctrl дарж гүйлгэнэ үү', 'Hold Ctrl and scroll to zoom'],
  zoomIn: ['Томруулах', 'Zoom in'], zoomOut: ['Жижигрүүлэх', 'Zoom out'], resetMap: ['Анхны байрлал', 'Reset view'],
  schematic: ['Схем зураг', 'Schematic map'],
  district: ['Дүүрэг', 'District'],
  showOnMap: ['Газрын зураг дээр харах', 'Show on map'],

  dataTitle: ['Хотын өгөгдөл', 'City data'],
  dataDesc: ['Бодит цагийн хэмжилт ба нээлттэй статистик. Утгууд 5 секунд тутам шинэчлэгдэнэ.', 'Live readings and open statistics, refreshed every 5 seconds.'],
  live: ['Шууд', 'Live'],
  updated: ['Шинэчлэгдсэн', 'Updated'],
  aqi24: ['Сүүлийн 24 цаг, AQI', 'Last 24 hours, AQI'],
  aqiAdvice: ['Ихэнх хүнд аюулгүй. Хүүхэд, ахмад настан, амьсгалын замын өвчтэй хүмүүс гадаа удаан байхгүй байхыг зөвлөж байна.', 'Fine for most people. Children, older adults and people with breathing conditions should limit long outdoor activity.'],
  aqiGood: ['Сайн', 'Good'], aqiMod: ['Дунд зэрэг', 'Moderate'], aqiUsg: ['Мэдрэг бүлэгт муу', 'Unhealthy for sensitive groups'], aqiBad: ['Эрүүл мэндэд муу', 'Unhealthy'],
  feels: ['Мэдрэгдэх', 'Feels like'], wind: ['Салхи', 'Wind'], humidity: ['Чийгшил', 'Humidity'], windDir: ['баруун хойноос', 'from NW'],
  congestion: ['Түгжрэлийн индекс', 'Congestion index'],
  busiest: ['Хамгийн ачаалалтай', 'Busiest roads'],
  population: ['Хүн ам', 'Population'],
  popNote: ['Дүүргээр, 2026 оны тооцоо', 'By district, 2026 estimate'],
  budgetExec: ['Төсвийн гүйцэтгэл', 'Budget execution'],
  budgetNote: ['2026 оны төсөв {v}, улирлаар', '2026 budget {v}, by quarter'],
  plan: ['Төлөвлөгөө', 'Plan'], actual: ['Гүйцэтгэл', 'Actual'],

  evTitle: ['Арга хэмжээ', 'Events'],
  evDesc: ['Хотод болох соёл, спорт, иргэний оролцооны арга хэмжээ', 'Culture, sport and civic events across the city'],
  f_today: ['Өнөөдөр', 'Today'], f_weekend: ['Энэ амралтын өдөр', 'This weekend'], f_free: ['Үнэгүй', 'Free'],
  v_list: ['Жагсаалт', 'List'], v_cal: ['Хуанли', 'Calendar'], v_map: ['Газрын зураг', 'Map'],
  free: ['Үнэгүй', 'Free'],
  save: ['Хадгалах', 'Save'], saved: ['Хадгалсан', 'Saved'],
  savedT: ['Хадгаллаа', 'Saved'], unsavedT: ['Хадгалснаас хаслаа', 'Removed from saved'],
  noEvents: ['Энэ өдөр тохирох арга хэмжээ алга. Өөр өдөр сонгоно уу.', 'Nothing matches on this day. Pick another date.'],
  noEventsF: ['Энэ шүүлтүүрт тохирох арга хэмжээ алга.', 'No events match this filter.'],
  eventsOn: ['{d}-ний арга хэмжээ', 'Events on {d}'],

  trTitle: ['Ил тод байдал', 'Transparency'],
  trDesc: ['Хотын шийдвэр, худалдан авалт бүрэн нээлттэй. Баримт бүрийг дугаар, нэрээр нь хайна.', 'City decisions and procurement, fully open. Search any document by number or title.'],
  tr_res: ['Тогтоол', 'Resolutions'], tr_ord: ['Захирамж, шийдвэр', 'Orders'], tr_tender: ['Тендер', 'Tenders'],
  docSearch: ['Дугаар, нэрээр хайх', 'Search by number or title'],
  inForce: ['Хүчин төгөлдөр', 'In force'], tOpen: ['Нээлттэй', 'Open'], tEval: ['Үнэлгээ хийгдэж буй', 'Under evaluation'], tAwarded: ['Гэрээ байгуулсан', 'Awarded'],
  daysLeft: ['{n} хоног үлдсэн', '{n} days left'], closesToday: ['Өнөөдөр хаагдана', 'Closes today'],
  view: ['Харах', 'View'],
  trStat1: ['Энэ онд нийтэлсэн шийдвэр', 'Decisions published this year'],
  trStat2: ['Нээлттэй тендер', 'Open tenders'],
  trStat3: ['Гэрээний нийт дүн', 'Contract value'],
  trStat4: ['Хүсэлтэд хариу өгөх дундаж хугацаа', 'Average reply time to requests'],
  days: ['хоног', 'days'],
  bidBtn: ['Тендерт оролцох', 'Submit a bid'],
  bidSent: ['Оролцох хүсэлт бүртгэгдлээ', 'Bid registration received'],
  docNote: ['Баримтын бүрэн эхийг Нийслэлийн ИТХ-ын албан ёсны архиваас үзнэ.', 'The full text is held in the official City Council archive.'],
  tl_pub: ['Зарласан', 'Published'], tl_bids: ['Материал хүлээн авах', 'Bids due'], tl_eval: ['Үнэлгээ', 'Evaluation'], tl_contract: ['Гэрээ', 'Contract'],

  aboutTitle: ['Хотын тухай', 'About the city'],
  aboutDesc: ['Монгол Улсын нийслэл, улсын хүн амын бараг тал хувь амьдардаг хот.', "Mongolia's capital, home to almost half of the country's people."],
  leadership: ['Удирдлагын бүтэц', 'How the city is governed'],
  orgs: ['Харьяа байгууллагууд', 'City agencies'],
  founded: ['Үүсгэн байгуулагдсан', 'Founded'], area: ['Нутаг дэвсгэр', 'Area'], admin: ['Засаг захиргаа', 'Administration'], elevation: ['Далайн түвшнээс дээш', 'Elevation'],
  adminV: ['9 дүүрэг, 204 хороо', '9 districts, 204 khoroos'],

  contact: ['Холбоо барих', 'Contact'],
  hotline: ['Иргэдийн санал хүсэлтийн утас, 24/7', 'Citizen hotline, 24/7'],
  emergency: ['Яаралтай тусламж', 'Emergency'],
  fire: ['Гал', 'Fire'], police: ['Цагдаа', 'Police'], ambulance: ['Түргэн тусламж', 'Ambulance'],
  digest: ['Долоо хоногийн тойм', 'Weekly digest'],
  digestD: ['Хотын гол мэдээ, хуваарь, хаалтыг и-мэйлээр.', 'Key city news, schedules and closures by email.'],
  email: ['И-мэйл хаяг', 'Email address'],
  subscribe: ['Бүртгүүлэх', 'Subscribe'], subscribed: ['Бүртгүүллээ. Баярлалаа!', 'Subscribed. Thank you!'],
  badEmail: ['И-мэйл хаягаа зөв оруулна уу.', 'Enter a valid email address.'],
  conceptNote: ['ulaanbaatar.mn-ийн шинэчилсэн концепц. Мэдээг ulaanbaatar.mn-ээс товчлон авсан, бусад тоо баримт жишээ болно.', 'A redesign concept for ulaanbaatar.mn. News is summarised from ulaanbaatar.mn; other figures are illustrative.'],
  srcNote: ['Энэ бол товчлол. Бүрэн эхийг ulaanbaatar.mn сайтаас уншина уу.', 'This is a summary. Read the full article on ulaanbaatar.mn.'],
  srcLink: ['Эх сурвалж', 'Source'],
  adminHist: ['Засаг захиргааны нэрийн түүх', 'A century of city administration'],
  adminHistD: ['Эх сурвалж: ulaanbaatar.mn/about', 'Source: ulaanbaatar.mn/about'],
  privacy: ['Нууцлал', 'Privacy'], access: ['Хүртээмж', 'Accessibility'], openData: ['Нээлттэй өгөгдөл', 'Open data'],
  f_services: ['Үйлчилгээ', 'Services'], f_info: ['Мэдээлэл', 'Information'],

  rTitle: ['Эрсдэл мэдээлэх', 'Report a hazard'],
  rEmergency: ['Амь нас, эрүүл мэндэд аюултай бол шууд 101, 102, 103 руу залгана уу.', 'If anyone is in danger, call 101, 102 or 103 now.'],
  rS1: ['Юу болсон бэ?', 'What did you see?'], rS2: ['Хаана болсон бэ?', 'Where is it?'], rS3: ['Дэлгэрэнгүй', 'Details'],
  rStep: ['{n}/3-р алхам', 'Step {n} of 3'],
  locate: ['Миний байршлыг ашиглах', 'Use my location'],
  tapMap: ['Газрын зураг дээр дарж байршлаа заана уу.', 'Tap the map to set the location.'],
  pickedIn: ['Сонгосон байршил: {d}', 'Selected: {d}'],
  desc: ['Тайлбар', 'Description'],
  descPh: ['Жишээ нь: 23-р байрны урд 1 метр орчим нүх гарсан, орой харанхуй байна.', 'e.g. A metre-wide pothole outside building 23, unlit at night.'],
  photo: ['Зураг хавсаргах', 'Attach a photo'],
  photoOpt: ['Заавал биш', 'Optional'],
  track: ['Миний буланд явцыг хянах', 'Track progress in My page'],
  continue: ['Үргэлжлүүлэх', 'Continue'], back: ['Буцах', 'Back'], submit: ['Мэдээлэх', 'Report'],
  rDone: ['Мэдээлэл бүртгэгдлээ', 'Report received'],
  rDoneD: ['Хянах дугаар {id}. 30 минутын дотор хариуцах байгууллагад шилжүүлж, явцыг Миний булан хэсэгт мэдэгдэнэ.', 'Tracking number {id}. It goes to the responsible agency within 30 minutes; follow progress in My page.'],
  trackIt: ['Явцыг харах', 'Track progress'],
  needCat: ['Төрлөө сонгоно уу', 'Choose a type first'],

  vTitle: ['Санал өгөх', 'Have your say'],
  vPoll: ['Санал асуулга', 'Poll'], vIdea: ['Санал хүсэлт', 'Suggestion'],
  pollQ: ['2027 оны хорооны хөгжлийн сангаар юуг нэн тэргүүнд хийх вэ?', 'What should the 2027 khoroo development fund do first?'],
  pollUntil: ['Санал авах хугацаа: {d} хүртэл', 'Open until {d}'],
  voteBtn: ['Саналаа өгөх', 'Cast my vote'],
  voted: ['Таны санал бүртгэгдлээ', 'Your vote is in'],
  totalVotes: ['Нийт {n} санал', '{n} votes'],
  yourPick: ['Таны сонголт', 'Your choice'],
  topic: ['Сэдэв', 'Topic'],
  ideaPh: ['Хотод юуг өөрчлөх вэ? Санаагаа бичээрэй.', 'What would you change in the city?'],
  ideaSend: ['Илгээх', 'Send'], ideaSent: ['Санал илгээгдлээ. 14 хоногт хариу өгнө.', 'Suggestion sent. You will get a reply within 14 days.'],
  toGov: ['Хүлээн авагч: Нийслэлийн Засаг дарга', 'To: the Governor of the Capital City'],
  needText: ['Саналаа бичнэ үү', 'Write your suggestion first'],

  danTitle: ['ДАН-аар нэвтрэх', 'Sign in with DAN'],
  danDesc: ['Төрийн цахим үйлчилгээний нэгдсэн нэвтрэлт. Нэг удаа нэвтэрч бүх үйлчилгээгээ авна.', 'The single sign-in for government e-services. One login for everything.'],
  danApp: ['И-Монголиа апп', 'e-Mongolia app'], danCode: ['Нэг удаагийн код', 'One-time code'], danBank: ['Интернэт банк', 'Internet bank'],
  scanQr: ['Апп-аараа QR кодыг уншуулна уу', 'Scan the QR code with the app'],
  waiting: ['Баталгаажуулалт хүлээж байна', 'Waiting for confirmation'],
  regPh: ['Регистрийн дугаар', 'Register number'], sendCode: ['Код илгээх', 'Send code'], codePh: ['6 оронтой код', '6-digit code'], codeSent: ['Бүртгэлтэй утас руу код илгээлээ', 'Code sent to your registered phone'],
  signIn: ['Нэвтрэх', 'Sign in'],
  bankPick: ['Банкаа сонгоно уу', 'Choose your bank'],
  demoNote: ['Концепц: дурын утга оруулахад нэвтэрнэ.', 'Concept: any value signs you in.'],
  signedIn: ['Амжилттай нэвтэрлээ', 'Signed in'],
  myCorner: ['Миний булан', 'My page'],
  logout: ['Гарах', 'Sign out'], loggedOut: ['Системээс гарлаа', 'Signed out'],

  hello: ['Сайн байна уу, {n}', 'Hello, {n}'],
  my_over: ['Тойм', 'Overview'], my_req: ['Миний хүсэлтүүд', 'My requests'], my_kh: ['Миний хороо', 'My khoroo'],
  s0: ['Хүлээн авсан', 'Received'], s1: ['Шилжүүлсэн', 'Assigned'], s2: ['Явцад байна', 'In progress'], s3: ['Шийдвэрлэсэн', 'Resolved'],
  newReq: ['Шинэ хүсэлт', 'New request'],
  notifs: ['Мэдэгдэл', 'Notifications'],
  payments: ['Төлбөр', 'Payments'], pay: ['Төлөх', 'Pay'], paid: ['Төлөгдсөн', 'Paid'], paidT: ['Төлбөр төлөгдлөө', 'Payment complete'], due: ['Төлөх хугацаа {d}', 'Due {d}'],
  savedItems: ['Хадгалсан арга хэмжээ', 'Saved events'], noSaved: ['Хадгалсан арга хэмжээ алга. Арга хэмжээн дээрх хадгалах тэмдгийг дарна уу.', 'No saved events yet. Tap the bookmark on any event.'],
  khGov: ['Хорооны Засаг дарга', 'Khoroo governor'], hours: ['Ажлын цаг', 'Office hours'], residents: ['Оршин суугч', 'Residents'], households: ['Өрх', 'Households'],
  nearby: ['Ойролцоох үйлчилгээ', 'Nearby services'], khNotices: ['Хорооны зар', 'Khoroo notices'],
  reqAgency: ['Хариуцагч', 'Handled by'],
  myStats1: ['Нээлттэй хүсэлт', 'Open requests'], myStats2: ['Шинэ мэдэгдэл', 'New notifications'], myStats3: ['Төлөх төлбөр', 'Payments due'],
  noReq: ['Танд одоогоор хүсэлт алга.', 'You have no requests yet.'],

  chatTitle: ['AI туслах', 'AI assistant'],
  chatOn: ['Хотын үйлчилгээний талаар асуугаарай', 'Ask about city services'],
  chatFallback: ['Түгээмэл асуултад бэлэн хариултаар туслана', 'Answers common questions'],
  chatGreet: ['Сайн байна уу! Би Улаанбаатар хотын AI туслах. Үйлчилгээ, хуваарь, төлбөр, агаарын чанарын талаар асуугаарай.', "Hi! I'm Ulaanbaatar's AI assistant. Ask me about services, schedules, payments or air quality."],
  chatPh: ['Асуултаа бичнэ үү', 'Type your question'],
  thinking: ['Бодож байна', 'Thinking'],
  stop: ['Зогсоох', 'Stop'],
  send: ['Илгээх', 'Send'],
  chatNote: ['AI алдаа гаргаж болзошгүй. Чухал мэдээллийг 1200 утсаар баталгаажуулна уу.', 'AI can make mistakes. Confirm important details on 1200.'],
  chatErr: ['Одоогоор хариулж чадсангүй. Дахин илгээнэ үү.', "Couldn't answer just now. Send it again."],
  chatBusy: ['Хэт олон хүсэлт ирлээ. Хэсэг хүлээгээд дахин оролдоно уу.', 'Too many requests right now. Wait a moment and try again.'],
  chatRefused: ['Энэ асуултад хариулах боломжгүй. Өөрөөр асууж үзнэ үү.', "I can't answer that. Try asking another way."],
  chatTip: ['Асуух зүйл байна уу?', 'Got a question?'],
  chatOpen: ['AI туслахыг нээх', 'Open AI assistant'],
  restartChat: ['Шинээр эхлэх', 'New chat'],

  s_services: ['Үйлчилгээ', 'Services'], s_news: ['Мэдээ', 'News'], s_projects: ['Төсөл', 'Projects'], s_events: ['Арга хэмжээ', 'Events'], s_sits: ['Амьдралын нөхцөл', 'Life events'],
  popular: ['Түгээмэл хайлт', 'Popular searches'],
  escClose: ['хаах', 'to close'],
  bb_home: ['Нүүр', 'Home'], bb_services: ['Үйлчилгээ', 'Services'], bb_report: ['Мэдээлэх', 'Report'], bb_news: ['Мэдээ', 'News'], bb_my: ['Миний', 'Me'],
  share: ['Холбоос хуулах', 'Copy link'], copied: ['Холбоос хуулагдлаа', 'Link copied'],
  helpful: ['Энэ мэдээлэл хэрэгтэй байсан уу?', 'Was this useful?'], thanks: ['Санал өгсөнд баярлалаа', 'Thanks for the feedback'],
  related: ['Холбоотой мэдээ', 'Related'],
  yes: ['Тийм', 'Yes'], no: ['Үгүй', 'No'],
  svcSteps: ['Хэрхэн авах вэ', 'How it works'],
  svcTime: ['Хугацаа', 'Time'], svcFee: ['Төлбөр', 'Fee'], svcFree: ['Үнэ төлбөргүй', 'Free'], svcDocs: ['Бүрдүүлэх зүйл', 'You will need'],
  openSys: ['Систем рүү орох', 'Open the system'], sysDemo: ['Концепц: энд гадаад систем нээгдэнэ', 'Concept: the external system opens here'],
  requestSent: ['Хүсэлт илгээгдлээ. Явцыг Миний булан хэсгээс харна.', 'Request sent. Follow it in My page.'],
};

/* ================= Alerts (ticker) ================= */
const ALERTS = [
  { id: 'a1', i: 'droplets', k: ['Халуун ус тасарна', 'Hot water off'],
    t: ['Баянзүрх дүүргийн 4, 5, 26-р хороо, {t+2} – {t+4}, шугамын засвар', 'Bayanzürkh khoroos 4, 5 and 26, {t+2} – {t+4}, pipe repairs'],
    area: ['Баянзүрх дүүргийн 4, 5, 26-р хороо, нийт 214 байр', 'Bayanzürkh khoroos 4, 5 and 26, 214 buildings'],
    when: ['{t+2} 09:00 – {t+4} 21:00', '{t+2} 09:00 – {t+4} 21:00'],
    adv: ['Ус нөөцлөх, цахилгаан халаагуурыг хэт ачаалахгүй байх. Дулааны хангамж хэвийн үргэлжилнэ.', 'Store water ahead and avoid overloading electric heaters. Heating stays on.'] },
  { id: 'a2', i: 'construction', k: ['Замын хаалт', 'Road closure'],
    t: ['Энхтайвны өргөн чөлөө, Баруун 4 зам – Их тойруу, өнөө шөнө 22:00–06:00', 'Peace Avenue, West Crossroads to Ring Road, tonight 22:00–06:00'],
    area: ['Энхтайвны өргөн чөлөөний 1.8 км хэсэг, хоёр чиглэлд', '1.8 km of Peace Avenue, both directions'],
    when: ['Өнөө шөнө 22:00 – маргааш 06:00', 'Tonight 22:00 – tomorrow 06:00'],
    adv: ['Сөүлийн гудамж болон Их тойруугаар тойрч явна уу. Нийтийн тээврийн 7 чиглэл түр өөрчлөгдөнө.', 'Use Seoul Street or the Ring Road. Seven bus routes are temporarily diverted.'] },
  { id: 'a3', i: 'wind', k: ['Агаарын чанар', 'Air quality'],
    t: ['20:00 цагаас PM2.5 өсөх төлөвтэй, мэдрэг бүлгийнхэн гадаа удаан байхгүй байна уу', 'PM2.5 expected to rise after 20:00; sensitive groups should limit time outdoors'],
    area: ['Нийслэлийн төв 6 дүүрэг', 'All six central districts'],
    when: ['Өнөөдөр 20:00 – маргааш 10:00', 'Today 20:00 – tomorrow 10:00'],
    adv: ['Агаар цэвэршүүлэгчээ асааж, гадуур амны хаалт зүүнэ үү. Хүүхэд, ахмад настнууд гадаа удаан байхгүй байх.', 'Run air purifiers and wear a mask outdoors. Children and older adults should stay inside where possible.'] },
  { id: 'a4', i: 'zap', k: ['Цахилгаан тасарна', 'Power outage'],
    t: ['Хан-Уул дүүргийн 11-р хороо, {t+1} 10:00–16:00, хуваарьт засвар', 'Khan-Uul khoroo 11, {t+1} 10:00–16:00, scheduled maintenance'],
    area: ['Хан-Уул дүүргийн 11-р хороо, 3 дэд станц', 'Khan-Uul khoroo 11, three substations'],
    when: ['{t+1} 10:00 – 16:00', '{t+1} 10:00 – 16:00'],
    adv: ['Цахилгаан хэрэгслээ сүлжээнээс салгаж, лифт ашиглахгүй байна уу.', 'Unplug appliances and avoid lifts during the outage.'] },
];

/* ================= Rubrics ================= */
const RUB = {
  city: { c: '#1D5BFF', t: ['Хотын захиргаа', 'City hall'] },
  plan: { c: '#7C4DFF', t: ['Хот төлөвлөлт', 'Planning'] },
  transport: { c: '#0EA5E9', t: ['Тээвэр', 'Transport'] },
  env: { c: '#10A36A', t: ['Байгаль орчин', 'Environment'] },
  build: { c: '#F08C1A', t: ['Бүтээн байгуулалт', 'Development'] },
  edu: { c: '#0D9488', t: ['Боловсрол', 'Education'] },
  health: { c: '#DB2777', t: ['Эрүүл мэнд', 'Health'] },
  culture: { c: '#C026D3', t: ['Соёл', 'Culture'] },
  util: { c: '#64748B', t: ['Дэд бүтэц', 'Utilities'] },
  zar: { c: '#E5A800', t: ['Зар', 'Notice'] },
  biz: { c: '#C2410C', t: ['Бизнес', 'Business'] },
};

/* ================= News: summarised from ulaanbaatar.mn (each links to the original) ================= */
const NEWS_SRC = 'https://ulaanbaatar.mn/news/';
let HERO_ID = 'n23265', FEATURED_ID = 'n23262';
const NEWS = [
  { id: 'n23265', cat: 'biz', d: '2026-10-02 18:13', views: 679, mins: 3, img: 'skyline:dawn:21', act: 'biz', rel: ['n23269', 'n23264', 'n23276'],
    t: ['Улаанбаатарт гарааны бизнесийн хотхон байгуулна', 'Ulaanbaatar to build a startup town'],
    l: ['Нийслэлийн Бизнес инновацын газар Солонгосын Стартап, энтрепренер хөгжлийн хүрээлэн (KISED)-тэй хамтран гарааны бизнесийн хотхон байгуулах хурдасгуур хөтөлбөрийг 2026–2028 онд хэрэгжүүлж байна.', "The city's Business Innovation Department and Korea's startup institute KISED are running a 2026–2028 accelerator programme to build a startup town in Ulaanbaatar."],
    b: [['Төслийг эрчимжүүлэх зорилгоор Нийслэлийн Засаг даргын Тамгын газрын дарга Ү.Ганболд тэргүүтэй албаны хүмүүс KISED-тэй хамтран ажиллаж байна.', "To speed the project up, officials led by Ü. Ganbold, Chief of the Capital City Governor's Office, are working with KISED."]] },
  { id: 'n23277', br: 1, cat: 'transport', d: '2026-10-08 10:34', views: 123, img: 'road:day:77',
    t: ['Цахилгаан скүтер, мопед, дугуйн аюулгүй байдлыг сайжруулна', 'Push to make e-scooter, moped and bike travel safer'],
    l: ['Засаг даргын орлогч Г.Жаргалсайхан Эрүүл хотуудын түншлэлийн төлөөлөгчидтэй уулзаж, эдгээр тээврийн хэрэгслийн дэд бүтэц, аюулгүй хэрэглээ, замын хөдөлгөөний дүрмийн хэрэгжилтийг сайжруулах талаар ярилцлаа.', 'Deputy Governor G. Jargalsaikhan met the Partnership for Healthy Cities to discuss infrastructure, safe use and traffic-rule enforcement for these light vehicles.'] },
  { id: 'n23276', br: 1, cat: 'city', d: '2026-10-07 19:18', views: 254, img: 'civic:day:76',
    t: ['Хүний эрхэд суурилсан төсвийн хэлэлцүүлэг боллоо', 'Discussion held on human-rights-based budgeting'],
    l: ['Иргэдийн эрх бодитоор хангагдах төсөв боловсруулах зорилгоор Тамгын газарт хэлэлцүүлэг болж, яамд болон хүүхэд, гэр бүл, хөдөлмөр, нийгмийн хамгаалал, боловсролын асуудал хариуцсан албаны хүмүүс оролцлоо.', "The Governor's Office hosted a discussion on budgets that deliver residents' rights, joined by ministries and officials for children, family, labour, social protection and education."] },
  { id: 'n23275', br: 1, cat: 'edu', d: '2026-10-07 18:04', views: 176, img: 'school:day:75',
    t: ['Олон улсын олимпиадын амжилттай сурагчдыг шагналаа', 'Students honoured for international olympiad success'],
    l: ['Засаг даргын орлогч Г.Жаргалсайхан, Боловсролын газрын дарга Б.Амартүвшин нар олон улсын олимпиадад амжилт гаргасан сурагчдад баяр хүргэж, шагнал гардууллаа.', 'Deputy Governor G. Jargalsaikhan and Education Department head B. Amartuvshin congratulated and awarded students who excelled at international olympiads.'] },
  { id: 'n23274', br: 1, cat: 'env', d: '2026-10-06 21:57', views: 603, img: 'park:green:74',
    t: ['Улаанбаатар цэцэрлэгт хүрээлэнг нийслэл хариуцна', 'The city takes over Ulaanbaatar Park'],
    l: ['«Рио Тинто Монгол» ХХК-ийн байгуулж, 2024 онд нээсэн 10.2 га цэцэрлэгт хүрээлэнгийн менежментийг компани хоёр жил хариуцсаны эцэст нийслэлд албан ёсоор шилжүүллээ.', 'Rio Tinto Mongolia built the 10.2-hectare park, opened in 2024, and has formally handed its management to the city after two years.'],
    b: [['Хүрээлэн Үндэсний соёл амралтын хүрээлэнгийн баруун жигүүрт байрладаг бөгөөд задгай театр, хүүхдийн тоглоомын талбайтай.', "It sits in the west wing of the National Recreation Park and includes an open-air theatre and a children's playground."]] },
  { id: 'n23273', br: 1, cat: 'env', d: '2026-10-06 14:28', views: 441, img: 'park:dawn:73',
    t: ['Ахмадууд намрын мод тарих аянд нэгдлээ', 'Elders join the autumn tree-planting drive'],
    l: ['«Тэрбум мод» үндэсний хөдөлгөөний хүрээнд Нийслэлийн ахмадын хороо, Баянзүрх дүүргийн Ахмадын зөвлөлийн төлөөлөл Үндэсний цэцэрлэгт хүрээлэнд мод тарилаа.', "Under the national Billion Trees movement, members of the city elders' committee and the Bayanzürkh elders' council planted trees in the National Park."] },
  { id: 'n23272', br: 1, cat: 'util', d: '2026-10-06 11:51', views: 507, img: 'heat:winter:72',
    t: ['Дулаан хангамжийн сүлжээг шинэчлэх асуудлыг ЕХ-ны багтай хэлэлцлээ', 'Heating-network renewal discussed with an EU team'],
    l: ['Нийслэлийн эрчим хүч, дулаан хангамжийн салбарын төлөөлөл Европын Холбооны баг болон эрчим хүчний зөвлөхүүдтэй уулзаж, хотын эрчим хүчний шилжилт, цаашдын хамтын ажиллагааны талаар санал солилцлоо.', "The city's energy and heating officials met an EU team and energy advisers on Ulaanbaatar's energy transition and next steps."] },
  { id: 'n23271', br: 1, cat: 'util', d: '2026-10-05 19:28', views: 609, img: 'road:winter:71',
    t: ['Цас цэвэрлэгээний давс, бодисын нөөцийг 65%-иар нэмэгдүүлж байна', 'Road salt and de-icer stocks up 65% ahead of winter'],
    l: ['Баянзүрх дүүргийн өвөлжилтийн бэлтгэл 90% хүрчээ. Дүүрэгт 37 байгууллага 400 гаруй техникээр зам талбай цэвэрлэдэг бөгөөд Засаг дарга Б.Пүрэвдагва бэлтгэл ажилтай газар дээр нь танилцлаа.', 'Bayanzürkh is 90% ready for winter: 37 organisations clear its roads with 400+ machines. Governor B. Purevdagva inspected preparations on site.'] },
  { id: 'n23270', br: 1, cat: 'city', d: '2026-10-05 16:37', views: 620, img: 'civic:civic:70',
    t: ['Нийслэлийн өвөлжилтийн бэлтгэл 90% хүрлээ', "The city's winter readiness reaches 90%"],
    l: ['Удирдах ажилтнуудын ээлжит шуурхай зөвлөгөөнөөр мод тарилт, өвөлжилтийн бэлтгэл, эмнэлгүүдийн бэлэн байдал, «Нүхэн гарц» төслийн явц, 2026 оны төсвийн гүйцэтгэл, 2027 оны төсвийн төлөвлөлтийг хэлэлцлээ.', "The leadership's regular operations meeting reviewed tree planting, winter readiness, hospital preparedness, the underpass project, 2026 budget execution and 2027 budget planning."] },
  { id: 'n23269', zar: 1, cat: 'zar', d: '2026-10-05 15:47', views: 447,
    t: ['«Нүүрс-пиролизийн үйлдвэр» төслийн санал хүлээн авалт хаагдлаа', 'Proposals closed for the coal-pyrolysis plant project'],
    l: ['Төр, хувийн хэвшлийн түншлэлээр хэрэгжүүлэх төслийн санал хүлээн авах хугацаа 10-р сарын 5-ны 10:00 цагт дууссан. Ирсэн саналын талаарх мэдээллийг ажлын хэсэг танилцуулжээ.', 'Submissions for this public-private partnership project closed on 5 October at 10:00. The working group has shared details of the proposals received.'] },
  { id: 'n23267', br: 1, cat: 'transport', d: '2026-10-05 11:02', views: 725, img: 'road:dusk:67',
    t: ['Замын хөдөлгөөнийг зохицуулах Шуурхай штаб байгууллаа', 'A traffic operations HQ has been set up'],
    l: ['Засаг даргын захирамжаар замын хөдөлгөөний эрчмийг сайжруулж, нийтийн тээврийн хүртээмжийг нэмэгдүүлэх Шуурхай штаб байгуулагдав. Штаб нь Цөлжилттэй тэмцэх тухай НҮБ-ын конвенцын Талуудын 17-р бага хурлын үеэр хот даяар нэгдсэн байдлаар ажиллана.', "By the Governor's order, an operations HQ will keep traffic moving and improve public transport, working city-wide during the UN desertification convention's COP17."] },
  { id: 'n23266', cat: 'edu', d: '2026-10-02 18:25', views: 1083, img: 'build:day:66',
    t: ['Багш нарын гэр бүлд түрээслээд өмчлөх орон сууцны батламж гардуулав', 'Teacher families receive rent-to-own housing certificates'],
    l: ['Дэлхийн багш нарын 32, Монголын багш нарын 60 дахь удаагийн баярын өдрөөр нийслэлийн боловсролын салбарын шилдэг байгууллага, багш нарыг шагнаж, багш гэр бүлийн төлөөлөлд орон сууцны батламж гардууллаа.', "On Teachers' Day (the 32nd worldwide, Mongolia's 60th), the city honoured top schools and teachers and gave rent-to-own housing certificates to teacher families."] },
  { id: 'n23264', cat: 'util', d: '2026-10-02 18:02', views: 732, img: 'tech:navy:64',
    t: ['Монгол–Солонгосын хотын эрчим хүчний форум боллоо', 'Mongolia–Korea urban energy forum held'],
    l: ['Хотын Захирагчийн ажлын алба, Эрчим хүчний яам, Сөүлийн Үндэсний их сургуулийн хамтын ажиллагааны төв, Барилгын зураг төсөл зохиогчдын холбоо хамтран эрчим хүчний хэмнэлттэй Улаанбаатарын талаар форум зохион байгууллаа.', "The Mayor's Office, the Ministry of Energy, a Seoul National University cooperation centre and Mongolia's architects' association co-hosted a forum on an energy-efficient Ulaanbaatar."] },
  { id: 'n23262', cat: 'build', d: '2026-09-30 10:17', views: 1143, img: 'cable:day:62',
    t: ['Дүүжин замын тээвэр 12-р сард ашиглалтад орно', 'Cable car to open in December'],
    l: ['Нийтийн тээврийг төрөлжүүлж, түгжрэлийг бууруулах дүүжин замын барилга угсралт бүрэн дуусч, нийт гүйцэтгэл 90% хүрсэн. Одоо тохиргоо, туршилтын ажил үргэлжилж байна.', 'Construction of the cable car, meant to diversify transit and ease congestion, is finished and the project is 90% complete. Tuning and test runs are under way.'] },
  { id: 'n23261', cat: 'health', d: '2026-09-29 15:13', views: 1021, img: 'school:green:61',
    t: ['Томуугийн эсрэг дархлаажуулалт 67.2% хүрлээ', 'Flu vaccination reaches 67.2%'],
    l: ['9-р сарын 3-наас 10-р сарын 3 хүртэл үргэлжилсэн аяны хүрээнд 0–6 насны хүүхэд, жирэмсэн эмэгтэй, ахмад настан, боловсрол, эрүүл мэндийн ажилтан, архаг өвчтэй нийт 293,619 иргэнийг вакцинжуулахаар төлөвлөжээ.', 'The 3 September – 3 October campaign planned to vaccinate 293,619 high-risk residents: children aged 0–6, pregnant women, older people, education and health workers, and people with chronic conditions.'] },
  { id: 'n23257', cat: 'env', d: '2026-09-27 18:01', views: 1443, img: 'park:green:57',
    t: ['Үндэсний цэцэрлэгт хүрээлэнд мянган мод суулгалаа', '1,000 trees planted in the National Park'],
    l: ['«Тэрбум мод» үндэсний хөдөлгөөний хүрээнд намрын мод тарих нэгдсэн арга хэмжээ эхэлж, ногоон хөгжлийг дэмжих, уур амьсгалын өөрчлөлтийг сааруулах зорилгоор 1000 мод тарилаа.', 'The autumn planting drive under the Billion Trees movement opened with 1,000 trees, in support of green growth and climate action.'] },
];
/* Бодит мэдээ: build үед ulaanbaatar.mn API-аас татсан LIVE_NEWS (news.js). Гараар бэлдсэн мэдээтэй ID-аар нь нийлүүлнэ:
   текст, огноо, үзэлт, зураг нь бодит; англи орчуулга, рубрик, үйлдлийн товч, холбоотой мэдээ нь гараар бэлдсэнээс. */
(function mergeLiveNews() {
  if (typeof LIVE_NEWS === 'undefined' || !LIVE_NEWS.length) return;
  const cur = {}; NEWS.forEach((n) => { cur[n.id] = n; });
  const scn = { transport: 'road:day:', env: 'park:green:', build: 'skyline:dawn:', plan: 'skyline:dawn:' };
  const fresh = (d) => Date.now() - new Date(String(d).replace(' ', 'T') + ':00+08:00') < 36 * 3600e3;
  const live = LIVE_NEWS.map((x) => {
    const c = cur[x.id]; delete cur[x.id];
    if (!c) return Object.assign({}, x, { img: x.img || (scn[x.cat] || 'civic:day:') + x.id.slice(-2), br: fresh(x.d) ? 1 : 0 });
    return Object.assign({}, c, x, { cat: c.cat, img: x.img || c.img, br: c.br, t: [x.t[0], c.t[1]], l: [x.l[0], c.l[1]], sumEn: (c.b || []).map((p) => p[1]).filter(Boolean) });
  });
  NEWS.splice(0, NEWS.length, ...live, ...Object.values(cur));
})();
const INCOMING = [];
const GOV = ['n23271', 'n23270', 'n23257'];
const ADMIN_NAMES = [
  [1924, 'Нийслэл хотын түр захиргаа', 'Provisional Administration of the Capital'],
  [1925, 'Улаанбаатар хотын захиргааны хэрэг эрхлэх газар', 'Ulaanbaatar City Administrative Affairs Office'],
  [1932, 'Улаанбаатар хотын аймгийн захиргаа', 'Ulaanbaatar City Aimag Administration'],
  [1933, 'Улаанбаатар хотын захиргаа', 'Ulaanbaatar City Administration'],
  [1938, 'Улаанбаатар хотын захирах яам', 'Ulaanbaatar City Governing Ministry'],
  [1941, 'Улаанбаатар хотын захиргаа', 'Ulaanbaatar City Administration'],
  [1948, 'Улаанбаатар хотын хөдөлмөрчдийн бага хурал', "Ulaanbaatar Workers' Small Khural"],
  [1953, 'Хөдөлмөрчдийн ардын хурлын гүйцэтгэх захиргаа', "Executive of the Workers' People's Khural"],
  [1961, 'Ардын депутатуудын хурлын гүйцэтгэх захиргаа', "Executive of the People's Deputies' Khural"],
  [1992, 'Нийслэлийн Засаг даргын Тамгын газар', "Capital City Governor's Office"],
];

/* ================= Media ================= */
const MEDIA = [
  { type: 'live', img: 'civic:navy:31', viewers: 1240, t: ['Нийслэлийн ИТХ-ын ээлжит хуралдаан', 'City Council regular session'], d: ['Хуралдааны танхимаас шууд', 'Live from the council chamber'] },
  { type: 'video', img: 'bridge:day:32', dur: '12:34', t: ['Туул хурдны зам: дроноос харахад', 'Tuul Expressway from a drone'], d: ['2-р хэсгийн ажил 64% хүрлээ', 'Section 2 has reached 64%'] },
  { type: 'photo', img: 'skyline:dusk:33', n: 31, t: ['Намрын Улаанбаатар', 'Ulaanbaatar in autumn'], d: ['Фото сурвалжилга', 'Photo story'] },
  { type: 'podcast', img: 'ger:dusk:34', dur: '38:12', ep: '#24', t: ['«Хотын яриа»: Гэр хорооллыг хэрхэн дахин төлөвлөх вэ?', '"City Talk": how should ger districts be redeveloped?'], d: ['Хот төлөвлөгч, иргэдийн төлөөлөлтэй', 'With a planner and residents'] },
  { type: 'video', img: 'road:night:35', dur: '3:05', t: ['Ухаалаг гэрлэн дохио хэрхэн ажилладаг вэ', 'How the smart traffic lights work'], d: ['3 минутын тайлбар', 'A three-minute explainer'] },
  { type: 'photo', img: 'school:day:36', n: 18, t: ['Шинэ цэцэрлэгийн нээлт', 'A new kindergarten opens'], d: ['Сүхбаатар дүүрэг', 'Sükhbaatar District'] },
];
